
T4174.hs:45:12: error: [GHC-18872]
    • Couldn't match type ‘False’ with ‘True’
        arising from a use of ‘sync_large_objects’
    • In the expression: sync_large_objects
      In an equation for ‘testcase’: testcase = sync_large_objects
